# Generated by Django 5.1.3 on 2024-11-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('margen_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=10)),
                ('imagen', models.CharField(max_length=255)),
                ('imagen_portada', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'laboratorios',
            },
        ),
    ]
